robco_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
robco_trajectory_controller:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
        - drive0_joint
        - drive1_joint
        - drive2_joint
        - drive3_joint
        - drive4_joint
    gains:
<<<<<<< HEAD
        drive0_joint: {p: 0.03, d: 0, i: 0.005, i_clamp: 100}
        drive1_joint: {p: 0.03, d: 0, i: 0.005, i_clamp: 100}
        drive2_joint: {p: 0.03, d: 0, i: 0.005, i_clamp: 100}
        drive3_joint: {p: 0.03, d: 0, i: 0.005, i_clamp: 100}
        drive4_joint: {p: 0.03, d: 0, i: 0.005, i_clamp: 100}
        drive5_joint: {p: 0.03, d: 0, i: 0.005, i_clamp: 100}
=======
        drive0_joint: {p: 0.025, d: 0, i: 0.005, i_clamp: 100}
        drive1_joint: {p: 0.025, d: 0, i: 0.005, i_clamp: 100}
        drive2_joint: {p: 0.025, d: 0, i: 0.005, i_clamp: 100}
        drive3_joint: {p: 0.025, d: 0, i: 0.005, i_clamp: 100}
        drive4_joint: {p: 0.025, d: 0, i: 0.005, i_clamp: 100}
>>>>>>> 901656e8df4d30b4e1b4cedb4d3adc28b2341128
    state_publish_rate: 50
