robco_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
robco_trajectory_controller:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
        - drive0_joint
        - drive1_joint
        - drive2_joint
        - drive3_joint
        - drive4_joint
    gains:
        drive0_joint: {p: 0.001, d: 0, i: 0, i_clamp: 0.1}
        drive1_joint: {p: 0.001, d: 0, i: 0, i_clamp: 0.1}
        drive2_joint: {p: 0.001, d: 0, i: 0, i_clamp: 0.1}
        drive3_joint: {p: 0.001, d: 0, i: 0, i_clamp: 0.1}
        drive4_joint: {p: 0.001, d: 0, i: 0, i_clamp: 0.1}
    state_publish_rate: 1
